version: '3.8'

services:
  lifehub-server:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    image: lifehub_server:latest
    container_name: lifehub_server
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_URL=${OLLAMA_URL}
      - OLLAMA_MODEL=${OLLAMA_MODEL}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - paddleocr-cache:/root/.paddleocr
    restart: unless-stopped

volumes:
  paddleocr-cache:
